const stylesPropsToInject = [
  'style',
  'flexBasis',
  'flex',
  'top',
  'bottom',
  'right',
  'left',
  'width',
  'height',
  'marginRight',
  'marginLeft',
  'marginBottom',
  'margin',
  'marginTop',
  'marginX',
  'marginY',
  'padding',
  'paddingLeft',
  'paddingRight',
  'paddingX',
  'paddingY',
  'borderRadius',
  'borderEndEndRadius',
  'borderTopLeftRadius',
  'borderEndStartRadius',
  'borderStartEndRadius',
  'borderTopRightRadius',
  'borderBottomLeftRadius',
  'borderStartStartRadius',
  'borderBottomRightRadius',
  'backgroundColor',
  'borderColor',
  'color'
];

export default stylesPropsToInject;
